AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MeetingMind - AI Meeting Intelligence Assistant

Globals:
  Function:
    Timeout: 60
    MemorySize: 256
    Runtime: python3.11
    Tracing: Active  # Enable X-Ray tracing for all Lambda functions
    Environment:
      Variables:
        MEETINGS_TABLE: !Ref MeetingsTable
        AUDIO_BUCKET:   !Ref AudioBucket
        REGION:         !Ref AWS::Region
        SNS_TOPIC_ARN:  !Ref ReminderTopic
        FRONTEND_URL:   https://dcfx593ywvy92.cloudfront.net
        SES_FROM_EMAIL: thecyberprinciples@gmail.com

Resources:

  # ── COGNITO ────────────────────────────────────────────────
  MeetingMindUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: meetingmind-users
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false

  MeetingMindUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref MeetingMindUserPool
      ClientName: meetingmind-web-client
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

  # ── S3 BUCKET (clean — no notification here) ──────────────
  AudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: meetingmind-audio-707411439284
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ["*"]
            AllowedMethods: [GET, PUT, POST, HEAD]
            AllowedHeaders: ["*"]
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldAudio
            Status: Enabled
            ExpirationInDays: 30

  # ── DYNAMODB ───────────────────────────────────────────────
  MeetingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: meetingmind-meetings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: meetingId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: meetingId
          KeyType: RANGE

  # ── SNS TOPIC ──────────────────────────────────────────────
  ReminderTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: meetingmind-reminders

  # ── API GATEWAY ────────────────────────────────────────────
  MeetingMindApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      TracingEnabled: true  # Enable X-Ray tracing for API Gateway
      Cors:
        AllowMethods: "'GET,POST,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt MeetingMindUserPool.Arn
        AddDefaultAuthorizerToCorsPreflight: false

  # ── LAMBDA: GET UPLOAD URL ─────────────────────────────────
  GetUploadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: meetingmind-get-upload-url
      CodeUri: functions/get-upload-url/
      Handler: app.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AudioBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref MeetingsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref MeetingMindApi
            Path: /upload-url
            Method: POST

  # ── LAMBDA: PROCESS MEETING ────────────────────────────────
  ProcessMeetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: meetingmind-process-meeting
      CodeUri: functions/process-meeting/
      Handler: app.lambda_handler
      Timeout: 900
      MemorySize: 512
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AudioBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref MeetingsTable
        - Statement:
            - Effect: Allow
              Action:
                - transcribe:StartTranscriptionJob
                - transcribe:GetTranscriptionJob
              Resource: "*"
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"

  # ── PERMISSION: allow S3 to invoke ProcessMeeting ─────────
  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn: ProcessMeetingFunction
    Properties:
      FunctionName: !GetAtt ProcessMeetingFunction.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt AudioBucket.Arn

  # ── CUSTOM RESOURCE: wire S3 notification AFTER both exist ─
  S3NotificationSetupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: meetingmind-s3-notification-setup
      InlineCode: |
        import boto3, json, urllib.request

        def handler(event, context):
            print("Event:", json.dumps(event))
            s3 = boto3.client('s3')
            bucket  = event['ResourceProperties']['BucketName']
            fn_arn  = event['ResourceProperties']['FunctionArn']
            req_type = event['RequestType']
            try:
                if req_type in ('Create', 'Update'):
                    s3.put_bucket_notification_configuration(
                        Bucket=bucket,
                        NotificationConfiguration={
                            'LambdaFunctionConfigurations': [{
                                'LambdaFunctionArn': fn_arn,
                                'Events': ['s3:ObjectCreated:*'],
                                'Filter': {'Key': {'FilterRules': [
                                    {'Name': 'prefix', 'Value': 'audio/'}
                                ]}}
                            }]
                        }
                    )
                elif req_type == 'Delete':
                    s3.put_bucket_notification_configuration(
                        Bucket=bucket,
                        NotificationConfiguration={}
                    )
                send(event, context, 'SUCCESS', {})
            except Exception as e:
                print(e)
                send(event, context, 'FAILED', {'Error': str(e)})

        def send(event, context, status, data):
            body = json.dumps({
                'Status': status,
                'Reason': data.get('Error',''),
                'PhysicalResourceId': event.get('PhysicalResourceId', context.log_stream_name),
                'StackId': event['StackId'],
                'RequestId': event['RequestId'],
                'LogicalResourceId': event['LogicalResourceId'],
                'Data': data
            }).encode()
            req = urllib.request.Request(event['ResponseURL'],
                data=body,
                headers={'Content-Type': ''},
                method='PUT')
            urllib.request.urlopen(req)
      Handler: index.handler
      Runtime: python3.11
      Timeout: 60
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref AudioBucket
        - Statement:
            - Effect: Allow
              Action: s3:PutBucketNotification
              Resource: !GetAtt AudioBucket.Arn

  S3NotificationSetup:
    Type: AWS::CloudFormation::CustomResource
    DependsOn:
      - AudioBucket
      - ProcessMeetingFunction
      - S3InvokeLambdaPermission
    Properties:
      ServiceToken: !GetAtt S3NotificationSetupFunction.Arn
      BucketName:   !Ref AudioBucket
      FunctionArn:  !GetAtt ProcessMeetingFunction.Arn

  # ── LAMBDA: LIST MEETINGS ──────────────────────────────────
  ListMeetingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: meetingmind-list-meetings
      CodeUri: functions/list-meetings/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MeetingsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref MeetingMindApi
            Path: /meetings
            Method: GET

  # ── LAMBDA: GET MEETING ────────────────────────────────────
  GetMeetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: meetingmind-get-meeting
      CodeUri: functions/get-meeting/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MeetingsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref MeetingMindApi
            Path: /meetings/{meetingId}
            Method: GET

  # ── LAMBDA: UPDATE ACTION ──────────────────────────────────
  UpdateActionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: meetingmind-update-action
      CodeUri: functions/update-action/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MeetingsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref MeetingMindApi
            Path: /meetings/{meetingId}/actions/{actionId}
            Method: PUT

  # ── LAMBDA: GET DEBT ANALYTICS ─────────────────────────────
  GetDebtAnalyticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: meetingmind-get-debt-analytics
      CodeUri: functions/get-debt-analytics/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MeetingsTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref MeetingMindApi
            Path: /debt-analytics
            Method: GET

  # ── LAMBDA: SEND REMINDERS ─────────────────────────────────
  SendRemindersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: meetingmind-send-reminders
      CodeUri: functions/send-reminders/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MeetingsTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ReminderTopic.TopicName
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 * * ? *)
            Description: Daily reminder at 8AM UTC

  # ── CLOUDWATCH DASHBOARD ───────────────────────────────────
  MeetingMindDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: MeetingMind-Production
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0, "y": 0, "width": 12, "height": 6,
              "properties": {
                "title": "Lambda Invocations and Errors",
                "metrics": [
                  ["AWS/Lambda", "Invocations", {"stat": "Sum", "label": "Invocations"}],
                  ["AWS/Lambda", "Errors", {"stat": "Sum", "label": "Errors"}]
                ],
                "period": 300,
                "region": "${AWS::Region}",
                "view": "timeSeries"
              }
            },
            {
              "type": "metric",
              "x": 12, "y": 0, "width": 12, "height": 6,
              "properties": {
                "title": "API Gateway Requests",
                "metrics": [
                  ["AWS/ApiGateway", "Count", {"stat": "Sum", "label": "Requests"}],
                  ["AWS/ApiGateway", "5XXError", {"stat": "Sum", "label": "5xx Errors"}]
                ],
                "period": 300,
                "region": "${AWS::Region}",
                "view": "timeSeries"
              }
            },
            {
              "type": "metric",
              "x": 0, "y": 6, "width": 12, "height": 6,
              "properties": {
                "title": "Lambda Duration ms",
                "metrics": [
                  ["AWS/Lambda", "Duration", {"stat": "Average", "label": "Avg Duration"}]
                ],
                "period": 300,
                "region": "${AWS::Region}",
                "view": "timeSeries"
              }
            },
            {
              "type": "metric",
              "x": 12, "y": 6, "width": 12, "height": 6,
              "properties": {
                "title": "DynamoDB Capacity",
                "metrics": [
                  ["AWS/DynamoDB", "ConsumedReadCapacityUnits", {"stat": "Sum", "label": "Reads"}],
                  ["AWS/DynamoDB", "ConsumedWriteCapacityUnits", {"stat": "Sum", "label": "Writes"}]
                ],
                "period": 300,
                "region": "${AWS::Region}",
                "view": "timeSeries"
              }
            }
          ]
        }
Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub "https://${MeetingMindApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  AudioBucketName:
    Description: S3 Bucket for audio
    Value: !Ref AudioBucket
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref MeetingMindUserPool
  UserPoolClientId:
    Description: Cognito Client ID
    Value: !Ref MeetingMindUserPoolClient
  MeetingsTableName:
    Description: DynamoDB Table
    Value: !Ref MeetingsTable
